export const ROLE_COLORS: Record<string, string> = {
  admin: "bg-purple-500/20 text-purple-400 border-purple-500/30",
  manager: "bg-blue-500/20 text-blue-400 border-blue-500/30",
  employee: "bg-green-500/20 text-green-400 border-green-500/30",
  security: "bg-orange-500/20 text-orange-400 border-orange-500/30",
  contractor: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
  visitor: "bg-slate-500/20 text-slate-400 border-slate-500/30",
};

export const DECISION_COLORS: Record<string, string> = {
  granted: "bg-green-500/20 text-green-400 border-green-500/30",
  denied: "bg-red-500/20 text-red-400 border-red-500/30",
  delayed: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
};

export const SEVERITY_COLORS: Record<string, string> = {
  low: "bg-blue-500/20 text-blue-400 border-blue-500/30",
  medium: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
  high: "bg-orange-500/20 text-orange-400 border-orange-500/30",
  critical: "bg-red-500/20 text-red-400 border-red-500/30",
};

export const SEVERITY_BAR_COLORS: Record<string, string> = {
  low: "#3b82f6",
  medium: "#eab308",
  high: "#f97316",
  critical: "#dc2626",
};

export const CHART_COLORS = {
  granted: "#22c55e",
  denied: "#ef4444",
  delayed: "#eab308",
  grid: "#1e293b",
  text: "#64748b",
  tooltip: { bg: "#1e293b", border: "#334155" },
};

export const MOCK_OVERVIEW = {
  total_accesses_today: 247,
  granted_today: 231,
  denied_today: 12,
  delayed_today: 4,
  active_alerts_count: 3,
  total_users: 20,
  total_access_points: 10,
};

export const MOCK_LOGS = [
  {
    id: 1,
    timestamp: "2026-02-14T09:23:00Z",
    decision: "granted" as const,
    risk_score: 0.05,
    badge_id_used: "B001",
    hour: 9,
    day_of_week: 5,
    is_weekend: false,
    access_frequency_24h: 5,
    time_since_last_access_min: 120,
    location_match: true,
    role_level: 3,
    is_restricted_area: false,
    method: "badge",
    user_id: 1,
    access_point_id: 1,
    user: {
      first_name: "Alice",
      last_name: "Martin",
      badge_id: "B001",
      role: "admin" as const,
    },
    access_point: {
      name: "Main Entrance A",
      building: "Building A",
      room: "Lobby-A",
    },
  },
  {
    id: 2,
    timestamp: "2026-02-14T09:21:00Z",
    decision: "granted" as const,
    risk_score: 0.08,
    badge_id_used: "B002",
    hour: 9,
    day_of_week: 5,
    is_weekend: false,
    access_frequency_24h: 6,
    time_since_last_access_min: 45,
    location_match: true,
    role_level: 3,
    is_restricted_area: false,
    method: "badge",
    user_id: 2,
    access_point_id: 3,
    user: {
      first_name: "Bob",
      last_name: "Dupont",
      badge_id: "B002",
      role: "manager" as const,
    },
    access_point: {
      name: "Engineering Office",
      building: "Building A",
      room: "Room-201",
    },
  },
  {
    id: 3,
    timestamp: "2026-02-14T09:18:00Z",
    decision: "denied" as const,
    risk_score: 0.89,
    badge_id_used: "B011",
    hour: 9,
    day_of_week: 5,
    is_weekend: false,
    access_frequency_24h: 2,
    time_since_last_access_min: 300,
    location_match: false,
    role_level: 1,
    is_restricted_area: true,
    method: "badge",
    user_id: 11,
    access_point_id: 4,
    user: {
      first_name: "Karim",
      last_name: "Hassan",
      badge_id: "B011",
      role: "employee" as const,
    },
    access_point: {
      name: "Server Room A3",
      building: "Building A",
      room: "Room-301",
    },
  },
  {
    id: 4,
    timestamp: "2026-02-14T09:15:00Z",
    decision: "delayed" as const,
    risk_score: 0.52,
    badge_id_used: "B005",
    hour: 9,
    day_of_week: 5,
    is_weekend: false,
    access_frequency_24h: 8,
    time_since_last_access_min: 15,
    location_match: true,
    role_level: 2,
    is_restricted_area: false,
    method: "badge",
    user_id: 5,
    access_point_id: 6,
    user: {
      first_name: "Eve",
      last_name: "Leclerc",
      badge_id: "B005",
      role: "security" as const,
    },
    access_point: {
      name: "Main Entrance B",
      building: "Building B",
      room: "Lobby-B",
    },
  },
  {
    id: 5,
    timestamp: "2026-02-14T09:10:00Z",
    decision: "granted" as const,
    risk_score: 0.03,
    badge_id_used: "B003",
    hour: 9,
    day_of_week: 5,
    is_weekend: false,
    access_frequency_24h: 4,
    time_since_last_access_min: 90,
    location_match: true,
    role_level: 2,
    is_restricted_area: false,
    method: "badge",
    user_id: 3,
    access_point_id: 3,
    user: {
      first_name: "Clara",
      last_name: "Nguyen",
      badge_id: "B003",
      role: "employee" as const,
    },
    access_point: {
      name: "Engineering Office",
      building: "Building A",
      room: "Room-201",
    },
  },
  {
    id: 6,
    timestamp: "2026-02-14T08:55:00Z",
    decision: "denied" as const,
    risk_score: 0.89,
    badge_id_used: "B013",
    hour: 8,
    day_of_week: 5,
    is_weekend: false,
    access_frequency_24h: 10,
    time_since_last_access_min: 10,
    location_match: false,
    role_level: 2,
    is_restricted_area: false,
    method: "badge",
    user_id: 13,
    access_point_id: 3,
    user: {
      first_name: "Marco",
      last_name: "Rossi",
      badge_id: "B013",
      role: "contractor" as const,
    },
    access_point: {
      name: "Engineering Office",
      building: "Building A",
      room: "Room-201",
    },
  },
  {
    id: 7,
    timestamp: "2026-02-14T08:45:00Z",
    decision: "granted" as const,
    risk_score: 0.0,
    badge_id_used: "B017",
    hour: 8,
    day_of_week: 5,
    is_weekend: false,
    access_frequency_24h: 1,
    time_since_last_access_min: 480,
    location_match: true,
    role_level: 3,
    is_restricted_area: true,
    method: "badge",
    user_id: 17,
    access_point_id: 4,
    user: {
      first_name: "Quinn",
      last_name: "Park",
      badge_id: "B017",
      role: "admin" as const,
    },
    access_point: {
      name: "Server Room A3",
      building: "Building A",
      room: "Room-301",
    },
  },
  {
    id: 8,
    timestamp: "2026-02-14T08:40:00Z",
    decision: "granted" as const,
    risk_score: 0.01,
    badge_id_used: "B007",
    hour: 8,
    day_of_week: 5,
    is_weekend: false,
    access_frequency_24h: 3,
    time_since_last_access_min: 60,
    location_match: true,
    role_level: 3,
    is_restricted_area: false,
    method: "badge",
    user_id: 7,
    access_point_id: 7,
    user: {
      first_name: "Grace",
      last_name: "Li",
      badge_id: "B007",
      role: "manager" as const,
    },
    access_point: {
      name: "HR Office B1",
      building: "Building B",
      room: "Room-101",
    },
  },
];

export const MOCK_ALERTS = [
  {
    id: 1,
    log_id: 4,
    alert_type: "badge_cloning",
    severity: "high" as const,
    status: "open" as const,
    is_resolved: false,
    confidence: 0.75,
    triggered_by: "ai_model",
    created_at: "2026-02-14T09:15:00Z",
    resolved_at: null,
    resolved_by: null,
    notes: null,
    description:
      "Badge B005 detected at 2 locations 3 minutes apart - possible badge cloning",
  },
  {
    id: 2,
    log_id: 6,
    alert_type: "unusual_hour",
    severity: "high" as const,
    status: "open" as const,
    is_resolved: false,
    confidence: 0.89,
    triggered_by: "ai_model",
    created_at: "2026-02-14T00:50:00Z",
    resolved_at: null,
    resolved_by: null,
    notes: null,
    description:
      "Contractor B013 accessed engineering at 23:50 - outside hours 09:00-17:00",
  },
  {
    id: 3,
    log_id: 3,
    alert_type: "unauthorized_zone",
    severity: "medium" as const,
    status: "open" as const,
    is_resolved: false,
    confidence: 0.95,
    triggered_by: "rule_engine",
    created_at: "2026-02-12T10:00:00Z",
    resolved_at: null,
    resolved_by: null,
    notes: null,
    description:
      "Employee B011 attempted restricted server room without sufficient clearance",
  },
];

export const MOCK_USERS = [
  {
    id: 1,
    badge_id: "B001",
    first_name: "Alice",
    last_name: "Martin",
    email: "alice.martin@company.com",
    phone: "+213550001001",
    role: "admin" as const,
    department: "IT",
    clearance_level: 5,
    is_active: true,
    created_at: "2024-01-01",
    last_seen_at: "2026-02-14T09:23:00Z",
  },
  {
    id: 2,
    badge_id: "B002",
    first_name: "Bob",
    last_name: "Dupont",
    email: "bob.dupont@company.com",
    phone: "+213550001002",
    role: "manager" as const,
    department: "Engineering",
    clearance_level: 4,
    is_active: true,
    created_at: "2024-01-01",
    last_seen_at: "2026-02-14T09:21:00Z",
  },
  {
    id: 3,
    badge_id: "B003",
    first_name: "Clara",
    last_name: "Nguyen",
    email: "clara.nguyen@company.com",
    phone: "+213550001003",
    role: "employee" as const,
    department: "Engineering",
    clearance_level: 2,
    is_active: true,
    created_at: "2024-01-01",
    last_seen_at: "2026-02-14T09:10:00Z",
  },
  {
    id: 5,
    badge_id: "B005",
    first_name: "Eve",
    last_name: "Leclerc",
    email: "eve.leclerc@company.com",
    phone: "+213550001005",
    role: "security" as const,
    department: "Security",
    clearance_level: 3,
    is_active: true,
    created_at: "2024-01-01",
    last_seen_at: "2026-02-14T09:15:00Z",
  },
  {
    id: 7,
    badge_id: "B007",
    first_name: "Grace",
    last_name: "Li",
    email: "grace.li@company.com",
    phone: "+213550001007",
    role: "manager" as const,
    department: "HR",
    clearance_level: 4,
    is_active: true,
    created_at: "2024-01-01",
    last_seen_at: "2026-02-14T08:40:00Z",
  },
  {
    id: 11,
    badge_id: "B011",
    first_name: "Karim",
    last_name: "Hassan",
    email: "karim.hassan@company.com",
    phone: "+213550001011",
    role: "employee" as const,
    department: "Marketing",
    clearance_level: 1,
    is_active: true,
    created_at: "2024-01-01",
    last_seen_at: "2026-02-14T09:18:00Z",
  },
  {
    id: 13,
    badge_id: "B013",
    first_name: "Marco",
    last_name: "Rossi",
    email: "marco.rossi@company.com",
    phone: "+213550001013",
    role: "contractor" as const,
    department: "Engineering",
    clearance_level: 2,
    is_active: true,
    created_at: "2024-01-01",
    last_seen_at: "2026-02-14T08:55:00Z",
  },
  {
    id: 17,
    badge_id: "B017",
    first_name: "Quinn",
    last_name: "Park",
    email: "quinn.park@company.com",
    phone: "+213550001017",
    role: "admin" as const,
    department: "IT",
    clearance_level: 5,
    is_active: true,
    created_at: "2024-01-01",
    last_seen_at: "2026-02-14T08:45:00Z",
  },
  {
    id: 19,
    badge_id: "B019",
    first_name: "Steve",
    last_name: "Blanc",
    email: "steve.blanc@company.com",
    phone: null,
    role: "visitor" as const,
    department: null,
    clearance_level: 1,
    is_active: false,
    created_at: "2024-01-01",
    last_seen_at: null,
  },
  {
    id: 20,
    badge_id: "B020",
    first_name: "Tina",
    last_name: "Koch",
    email: "tina.koch@company.com",
    phone: "+213550001020",
    role: "manager" as const,
    department: "IT",
    clearance_level: 4,
    is_active: true,
    created_at: "2024-01-01",
    last_seen_at: "2026-02-14T09:00:00Z",
  },
];
